version: 2.1
executors:
  go-docker:
    docker:
      - image: circleci/golang:1.16

jobs:
  lint-dockerfile:
    executor: go-docker
    steps:
      - checkout
      - run: 
          name: Install hadolint
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run: 
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: go-docker
    steps:
      - checkout
      - run: 
          name: Test app
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker build -t my-app-ui:${CIRCLE_BUILD_NUM} .
            docker push my-app-ui:${CIRCLE_BUILD_NUM}
            docker tag my-app-ui:${CIRCLE_BUILD_NUM} my-app-ui:latest
            docker push my-app-ui:latest
workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs
      - test-app:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          filters:
            branches:
              only: karsajobs
