version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/golang:1.14
jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            wget -O - https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
            chmod +x hadolint
            ./hadolint Dockerfile
  test-app:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Test App
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
            docker build -t my-app-ui:${CIRCLE_BUILD_NUM} .
            docker push my-app-ui:${CIRCLE_BUILD_NUM}
            docker tag my-app-ui:${CIRCLE_BUILD_NUM} my-app-ui:latest
            docker push my-app-ui:latest
workflows:
  version: 2
  build-and-push:
    jobs:
      - lint-dockerfile:
          filters:
            branches:
              only: karsajobs
      - test-app:
          filters:
            branches:
              only: karsajobs
      - build-app-karsajobs:
          filters:
            branches:
              only: karsajobs
